/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CflSideDrawer {
        "isopen": boolean;
        "open": () => Promise<void>;
        "title": string;
    }
}
declare global {
    interface HTMLCflSideDrawerElement extends Components.CflSideDrawer, HTMLStencilElement {
    }
    var HTMLCflSideDrawerElement: {
        prototype: HTMLCflSideDrawerElement;
        new (): HTMLCflSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "cfl-side-drawer": HTMLCflSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface CflSideDrawer {
        "isopen"?: boolean;
        "title"?: string;
    }
    interface IntrinsicElements {
        "cfl-side-drawer": CflSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cfl-side-drawer": LocalJSX.CflSideDrawer & JSXBase.HTMLAttributes<HTMLCflSideDrawerElement>;
        }
    }
}
